[theme]
name = "catppuccin-mocha"
theme_type = "dark"

[theme.ansi]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[theme.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[theme.syntax]
comment = "#6c7086"
string = "#a6e3a1"
number = "#fab387"
keyword = "#cba6f7"
function = "#89b4fa"
variable = "#cdd6f4"
type_name = "#f5e0dc"
operator = "#89dceb"

[theme.ui]
# 背景色层次
bg_100 = "#11111b"
bg_200 = "#1e1e2e"
bg_300 = "#313244"
bg_400 = "#45475a"
bg_500 = "#585b70"
bg_600 = "#6c7086"
bg_700 = "#7f849c"

# 边框层次
border_200 = "rgba(69, 71, 90, 0.2)"
border_300 = "rgba(69, 71, 90, 0.4)"
border_400 = "rgba(69, 71, 90, 0.6)"

# 文本层次
text_100 = "#cdd6f4"
text_200 = "#bac2de"
text_300 = "#a6adc8"
text_400 = "#9399b2"
text_500 = "#6c7086"

# 状态颜色
primary = "#89b4fa"
primary_hover = "#74c7ec"
primary_alpha = "rgba(137, 180, 250, 0.15)"
success = "#a6e3a1"
warning = "#f9e2af"
error = "#f38ba8"
info = "#94e2d5"

# 交互状态
hover = "#313244"
active = "#45475a"
focus = "#89b4fa"
selection = "rgba(137, 180, 250, 0.3)"

# 阴影和其他UI变量
shadow_sm = "0 1px 3px 0 rgba(0, 0, 0, 0.12)"
shadow_md = "0 4px 6px -1px rgba(0, 0, 0, 0.1)"
font_family = "'JetBrains Mono', 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace"
border_radius = "8px"
border_radius_lg = "12px"
