# OrbitX 深色主题配置文件
# 主题名称: Dark
# 适用场景: 深色模式，护眼，夜间使用

[theme]
name = "dark"                   # 主题名称，必须与文件名一致
theme_type = "dark"             # 主题类型: dark(深色), light(浅色)

# 基础颜色配置
[theme.colors]
foreground = "#e6e6e6"          # 前景色 (文字颜色)
background = "#1e1e1e"          # 背景色
cursor = "#ffffff"              # 光标颜色
selection = "#3391ff"           # 选中文本的背景色

# ANSI 标准颜色 (普通亮度)
[theme.colors.ansi]
black = "#000000"               # 黑色 (ANSI 0)
red = "#cd3131"                 # 红色 (ANSI 1)
green = "#0dbc79"               # 绿色 (ANSI 2)
yellow = "#e5e510"              # 黄色 (ANSI 3)
blue = "#2472c8"                # 蓝色 (ANSI 4)
magenta = "#bc3fbc"             # 洋红色 (ANSI 5)
cyan = "#11a8cd"                # 青色 (ANSI 6)
white = "#e5e5e5"               # 白色 (ANSI 7)

# ANSI 明亮颜色 (高亮度)
[theme.colors.bright]
black = "#666666"               # 明亮黑色 (ANSI 8)
red = "#f14c4c"                 # 明亮红色 (ANSI 9)
green = "#23d18b"               # 明亮绿色 (ANSI 10)
yellow = "#f5f543"              # 明亮黄色 (ANSI 11)
blue = "#3b8eea"                # 明亮蓝色 (ANSI 12)
magenta = "#d670d6"             # 明亮洋红色 (ANSI 13)
cyan = "#29b8db"                # 明亮青色 (ANSI 14)
white = "#ffffff"               # 明亮白色 (ANSI 15)



# UI 界面颜色配置
[theme.ui]
primary = "#007acc"             # 主色调 (按钮、链接等)
border = "#3c3c3c"              # 边框颜色
background_secondary = "#252526" # 次要背景色
background_hover = "#2a2d2e"    # 悬停背景色
