# OrbitX 深色主题配置文件 - 全新层次系统
# 主题名称: Dark
# 适用场景: 深色模式，护眼，夜间使用

[theme]
name = "dark"
theme_type = "dark"



[theme.ansi]
black = "#000000"
red = "#cd3131"
green = "#0dbc79"
yellow = "#e5e510"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#11a8cd"
white = "#e5e5e5"

[theme.bright]
black = "#666666"
red = "#f14c4c"
green = "#23d18b"
yellow = "#f5f543"
blue = "#3b8eea"
magenta = "#d670d6"
cyan = "#29b8db"
white = "#ffffff"

[theme.syntax]
comment = "#6a9955"
keyword = "#569cd6"
string = "#ce9178"
number = "#b5cea8"
function = "#dcdcaa"
variable = "#9cdcfe"
type_name = "#4ec9b0"
operator = "#d4d4d4"

[theme.ui]
# 背景色层次
bg_100 = "#1a1a1a"
bg_200 = "#1e1e1e"
bg_300 = "#252526"
bg_400 = "#2d2d30"
bg_500 = "#3c3c3c"
bg_600 = "#4d4d4d"
bg_700 = "#5a5a5a"

# 边框层次
border_200 = "rgba(255, 255, 255, 0.08)"
border_300 = "rgba(255, 255, 255, 0.12)"
border_400 = "rgba(255, 255, 255, 0.16)"

# 文本层次
text_100 = "#ffffff"
text_200 = "#e0e0e0"
text_300 = "#cccccc"
text_400 = "#999999"
text_500 = "#666666"

# 状态颜色
primary = "#80c7ff"
primary_hover = "#66b3ff"
primary_alpha = "rgba(128, 199, 255, 0.1)"
success = "#0dbc79"
warning = "#ffcc02"
error = "#f44747"
info = "#75beff"

# 交互状态
hover = "#2a2d2e"
active = "#3c3c3c"
focus = "#80c7ff"
selection = "rgba(173, 214, 255, 0.3)"
