[theme]
name = "github-dark"
theme_type = "dark"

[theme.ansi]
black = "#484f58"
red = "#ff7b72"
green = "#7ce38b"
yellow = "#ffa657"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[theme.bright]
black = "#6e7681"
red = "#ffa198"
green = "#56d364"
yellow = "#ffdf5d"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#56d4dd"
white = "#f0f6fc"

[theme.syntax]
comment = "#8b949e"
string = "#7ce38b"
number = "#79c0ff"
keyword = "#ff7b72"
function = "#d2a8ff"
variable = "#f0f6fc"
type_name = "#ffa657"
operator = "#ff7b72"

[theme.ui]
# 背景色层次
bg_100 = "#010409"
bg_200 = "#0d1117"
bg_300 = "#161b22"
bg_400 = "#21262d"
bg_500 = "#30363d"
bg_600 = "#484f58"
bg_700 = "#6e7681"

# 边框层次
border_200 = "rgba(48, 54, 61, 0.2)"
border_300 = "rgba(48, 54, 61, 0.4)"
border_400 = "rgba(48, 54, 61, 0.6)"

# 文本层次
text_100 = "#f0f6fc"
text_200 = "#e6edf3"
text_300 = "#b1bac4"
text_400 = "#9198a1"
text_500 = "#6e7681"

# 状态颜色
primary = "#58a6ff"
primary_hover = "#388bfd"
primary_alpha = "rgba(88, 166, 255, 0.15)"
success = "#238636"
warning = "#9e6a03"
error = "#da3633"
info = "#1f6feb"

# 交互状态
hover = "#161b22"
active = "#21262d"
focus = "#58a6ff"
selection = "rgba(88, 166, 255, 0.25)"

# 阴影和其他UI变量
shadow_sm = "0 1px 0 rgba(1, 4, 9, 0.04)"
shadow_md = "0 3px 6px rgba(1, 4, 9, 0.12)"
font_family = "'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace"
border_radius = "6px"
border_radius_lg = "8px"
