[theme]
name = "gruvbox-dark"
theme_type = "dark"



[theme.ansi]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[theme.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[theme.syntax]
comment = "#928374"
string = "#b8bb26"
number = "#d3869b"
keyword = "#fb4934"
function = "#fabd2f"
variable = "#83a598"
type_name = "#8ec07c"
operator = "#fe8019"

[theme.ui]
# Gruvbox Dark 背景色层次
bg_100 = "#1d2021"
bg_200 = "#282828"
bg_300 = "#32302f"
bg_400 = "#3c3836"
bg_500 = "#504945"
bg_600 = "#665c54"
bg_700 = "#7c6f64"

# 边框层次
border_200 = "rgba(60, 56, 54, 0.3)"
border_300 = "rgba(60, 56, 54, 0.5)"
border_400 = "rgba(60, 56, 54, 0.7)"

# 文本层次
text_100 = "#ffffff"
text_200 = "#fbf1c7"
text_300 = "#ebdbb2"
text_400 = "#d5c4a1"
text_500 = "#928374"

# 状态颜色
primary = "#80c7ff"
primary_hover = "#66b3ff"
primary_alpha = "rgba(128, 199, 255, 0.1)"
success = "#98971a"
warning = "#d79921"
error = "#cc241d"
info = "#689d6a"

# 交互状态
hover = "#32302f"
active = "#3c3836"
focus = "#458588"
selection = "rgba(60, 56, 54, 0.8)"

# 阴影和其他UI变量
shadow_sm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)"
font_family = "'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace"
border_radius = "6px"
border_radius_lg = "8px"
