version = "1.0.0"
totalThemes = 10
customThemes = []

[lastUpdated]
secs_since_epoch = 1755799109
nanos_since_epoch = 43865000

[[builtinThemes]]
name = "light"
file = "light.toml"
type = "light"
builtin = true
fileSize = 1414

[builtinThemes.lastModified]
secs_since_epoch = 1755067778
nanos_since_epoch = 656688940

[[builtinThemes]]
name = "solarized-dark"
file = "solarized-dark.toml"
type = "dark"
builtin = true
fileSize = 1257

[builtinThemes.lastModified]
secs_since_epoch = 1755067818
nanos_since_epoch = 941779822

[[builtinThemes]]
name = "dark"
file = "dark.toml"
type = "dark"
builtin = true
fileSize = 1380

[builtinThemes.lastModified]
secs_since_epoch = 1755067775
nanos_since_epoch = 106386189

[[builtinThemes]]
name = "one-dark"
file = "one-dark.toml"
type = "dark"
builtin = true
fileSize = 1249

[builtinThemes.lastModified]
secs_since_epoch = 1755067785
nanos_since_epoch = 691702671

[[builtinThemes]]
name = "gruvbox-dark"
file = "gruvbox-dark.toml"
type = "dark"
builtin = true
fileSize = 1257

[builtinThemes.lastModified]
secs_since_epoch = 1755067814
nanos_since_epoch = 924253390

[[builtinThemes]]
name = "solarized-light"
file = "solarized-light.toml"
type = "light"
builtin = true
fileSize = 1275

[builtinThemes.lastModified]
secs_since_epoch = 1755067822
nanos_since_epoch = 488899867

[[builtinThemes]]
name = "tokyo-night"
file = "tokyo-night.toml"
type = "dark"
builtin = true
fileSize = 1257

[builtinThemes.lastModified]
secs_since_epoch = 1755067766
nanos_since_epoch = 369585825

[[builtinThemes]]
name = "dracula"
file = "dracula.toml"
type = "dark"
builtin = true
fileSize = 1248

[builtinThemes.lastModified]
secs_since_epoch = 1755067943
nanos_since_epoch = 527266130

[[builtinThemes]]
name = "monokai"
file = "monokai.toml"
type = "dark"
builtin = true
fileSize = 1248

[builtinThemes.lastModified]
secs_since_epoch = 1755067782
nanos_since_epoch = 164093190

[[builtinThemes]]
name = "nord"
file = "nord.toml"
type = "dark"
builtin = true
fileSize = 1241

[builtinThemes.lastModified]
secs_since_epoch = 1755067811
nanos_since_epoch = 356357322

[defaults]
lightTheme = "light"
darkTheme = "dark"
defaultTheme = "dark"
