# OrbitX 浅色主题配置文件 - 全新层次系统
# 主题名称: Light
# 适用场景: 浅色模式，白天使用，高对比度

[theme]
name = "light"
theme_type = "light"



[theme.ansi]
black = "#24292e"
red = "#d73a49"
green = "#28a745"
yellow = "#ffd33d"
blue = "#0366d6"
magenta = "#ea4aaa"
cyan = "#17a2b8"
white = "#f6f8fa"

[theme.bright]
black = "#586069"
red = "#cb2431"
green = "#22863a"
yellow = "#b08800"
blue = "#005cc5"
magenta = "#e36209"
cyan = "#0598bc"
white = "#fafbfc"

[theme.syntax]
comment = "#6a737d"
string = "#032f62"
number = "#005cc5"
keyword = "#d73a49"
function = "#6f42c1"
variable = "#e36209"
type_name = "#005cc5"
operator = "#d73a49"

[theme.ui]
# 浅色主题的背景色层次
bg_100 = "#ffffff"
bg_200 = "#fafafa"
bg_300 = "#f5f5f5"
bg_400 = "#f0f0f0"
bg_500 = "#e8e8e8"
bg_600 = "#e0e0e0"
bg_700 = "#d8d8d8"

# 浅色主题的边框层次
border_200 = "rgba(0, 0, 0, 0.08)"
border_300 = "rgba(0, 0, 0, 0.12)"
border_400 = "rgba(0, 0, 0, 0.16)"

# 浅色主题的文本层次
text_100 = "#000000"
text_200 = "#1a1a1a"
text_300 = "#333333"
text_400 = "#666666"
text_500 = "#999999"

# 状态颜色
primary = "#80c7ff"
primary_hover = "#66b3ff"
primary_alpha = "rgba(128, 199, 255, 0.1)"
success = "#28a745"
warning = "#ffc107"
error = "#dc3545"
info = "#17a2b8"

# 交互状态
hover = "#e8e8e8"
active = "#e0e0e0"
focus = "#80c7ff"
selection = "rgba(3, 102, 214, 0.3)"
