[theme]
name = "material-dark"
theme_type = "dark"

[theme.ansi]
black = "#263238"
red = "#f07178"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82b1ff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#eeffff"

[theme.bright]
black = "#546e7a"
red = "#f07178"
green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82b1ff"
magenta = "#c792ea"
cyan = "#89ddff"
white = "#ffffff"

[theme.syntax]
comment = "#546e7a"
string = "#c3e88d"
number = "#f78c6c"
keyword = "#c792ea"
function = "#82b1ff"
variable = "#eeffff"
type_name = "#ffcb6b"
operator = "#89ddff"

[theme.ui]
# 背景色层次
bg_100 = "#0f111a"
bg_200 = "#212121"
bg_300 = "#263238"
bg_400 = "#2e3c43"
bg_500 = "#37474f"
bg_600 = "#455a64"
bg_700 = "#546e7a"

# 边框层次
border_200 = "rgba(55, 71, 79, 0.2)"
border_300 = "rgba(55, 71, 79, 0.4)"
border_400 = "rgba(55, 71, 79, 0.6)"

# 文本层次
text_100 = "#ffffff"
text_200 = "#eeffff"
text_300 = "#b2ccd6"
text_400 = "#8796a5"
text_500 = "#546e7a"

# 状态颜色
primary = "#80cbc4"
primary_hover = "#4db6ac"
primary_alpha = "rgba(128, 203, 196, 0.15)"
success = "#c3e88d"
warning = "#ffcb6b"
error = "#f07178"
info = "#89ddff"

# 交互状态
hover = "#263238"
active = "#37474f"
focus = "#80cbc4"
selection = "rgba(128, 203, 196, 0.25)"

# 阴影和其他UI变量
shadow_sm = "0 2px 1px -1px rgba(0,0,0,.2), 0 1px 1px 0 rgba(0,0,0,.14)"
shadow_md = "0 3px 3px -2px rgba(0,0,0,.2), 0 3px 4px 0 rgba(0,0,0,.14)"
font_family = "'Roboto Mono', 'SF Mono', Monaco, 'Cascadia Code', Consolas, 'Courier New', monospace"
border_radius = "4px"
border_radius_lg = "8px"
