[theme]
name = "nord"
theme_type = "dark"

[theme.colors]
foreground = "#d8dee9"
background = "#2e3440"
cursor = "#d8dee9"
selection = "#434c5e"

[theme.colors.ansi]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[theme.colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[theme.syntax]
comment = "#616e88"
string = "#a3be8c"
number = "#b48ead"
keyword = "#81a1c1"
function = "#88c0d0"
variable = "#d8dee9"
type_name = "#8fbcbb"
operator = "#81a1c1"

[theme.ui]
primary = "#5e81ac"
secondary = "#616e88"
success = "#a3be8c"
warning = "#ebcb8b"
error = "#bf616a"
info = "#88c0d0"
border = "#434c5e"
divider = "#434c5e"
