[theme]
name = "nord"
theme_type = "dark"



[theme.ansi]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[theme.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[theme.syntax]
comment = "#616e88"
string = "#a3be8c"
number = "#b48ead"
keyword = "#81a1c1"
function = "#88c0d0"
variable = "#d8dee9"
type_name = "#8fbcbb"
operator = "#81a1c1"

[theme.ui]
# 背景色层次
bg_100 = "#2e3440"
bg_200 = "#3b4252"
bg_300 = "#434c5e"
bg_400 = "#4c566a"
bg_500 = "#5e81ac"
bg_600 = "#81a1c1"
bg_700 = "#8fbcbb"

# 边框层次
border_200 = "rgba(76, 86, 106, 0.25)"
border_300 = "rgba(76, 86, 106, 0.45)"
border_400 = "rgba(76, 86, 106, 0.65)"

# 文本层次
text_100 = "#eceff4"
text_200 = "#e5e9f0"
text_300 = "#d8dee9"
text_400 = "#a5b3c2"
text_500 = "#616e88"

# 状态颜色
primary = "#5e81ac"
primary_hover = "#81a1c1"
primary_alpha = "rgba(94, 129, 172, 0.15)"
success = "#a3be8c"
warning = "#ebcb8b"
error = "#bf616a"
info = "#88c0d0"

# 交互状态
hover = "#434c5e"
active = "#4c566a"
focus = "#5e81ac"
selection = "rgba(94, 129, 172, 0.3)"

# 阴影和其他UI变量
shadow_sm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)"
font_family = "'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace"
border_radius = "6px"
border_radius_lg = "8px"
