[theme]
name = "one-dark"
theme_type = "dark"



[theme.ansi]
black = "#282c34"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[theme.bright]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#ffffff"

[theme.syntax]
comment = "#5c6370"
keyword = "#c678dd"
string = "#98c379"
number = "#d19a66"
function = "#61afef"
variable = "#abb2bf"
type_name = "#e5c07b"
operator = "#56b6c2"

[theme.ui]
# One Dark 背景色层次
bg_100 = "#1e2127"
bg_200 = "#282c34"
bg_300 = "#2c313c"
bg_400 = "#353b45"
bg_500 = "#3e4451"
bg_600 = "#4b5263"
bg_700 = "#5c6370"

# 边框层次
border_200 = "rgba(62, 68, 81, 0.3)"
border_300 = "rgba(62, 68, 81, 0.5)"
border_400 = "rgba(62, 68, 81, 0.7)"

# 文本层次
text_100 = "#ffffff"
text_200 = "#abb2bf"
text_300 = "#9da5b4"
text_400 = "#7f848e"
text_500 = "#5c6370"

# 状态颜色
primary = "#80c7ff"
primary_hover = "#66b3ff"
primary_alpha = "rgba(128, 199, 255, 0.1)"
success = "#98c379"
warning = "#e5c07b"
error = "#e06c75"
info = "#56b6c2"

# 交互状态
hover = "#2c313c"
active = "#3e4451"
focus = "#61afef"
selection = "rgba(62, 68, 81, 0.8)"

# 阴影和其他UI变量
shadow_sm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)"
font_family = "'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace"
border_radius = "6px"
border_radius_lg = "8px"
