[theme]
name = "solarized-light"
theme_type = "light"

[theme.colors]
foreground = "#657b83"
background = "#fdf6e3"
cursor = "#586e75"
selection = "#eee8d5"

[theme.colors.ansi]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[theme.colors.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"



[theme.ui]
primary = "#268bd2"
border = "#eee8d5"
background_secondary = "#f7f1e8"
background_hover = "#f0ead7"
