[theme]
name = "solarized-dark"
theme_type = "dark"



[theme.ansi]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[theme.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"

[theme.syntax]
comment = "#586e75"
string = "#2aa198"
number = "#d33682"
keyword = "#859900"
function = "#268bd2"
variable = "#839496"
type_name = "#b58900"
operator = "#dc322f"

[theme.ui]
# Solarized Dark 背景色层次
bg_100 = "#001e27"
bg_200 = "#002b36"
bg_300 = "#073642"
bg_400 = "#0c4a5a"
bg_500 = "#586e75"
bg_600 = "#657b83"
bg_700 = "#839496"

# 边框层次
border_200 = "rgba(7, 54, 66, 0.3)"
border_300 = "rgba(7, 54, 66, 0.5)"
border_400 = "rgba(7, 54, 66, 0.7)"

# 文本层次
text_100 = "#ffffff"
text_200 = "#fdf6e3"
text_300 = "#eee8d5"
text_400 = "#93a1a1"
text_500 = "#586e75"

# 状态颜色
primary = "#80c7ff"
primary_hover = "#66b3ff"
primary_alpha = "rgba(128, 199, 255, 0.1)"
success = "#859900"
warning = "#b58900"
error = "#dc322f"
info = "#2aa198"

# 交互状态
hover = "#073642"
active = "#0c4a5a"
focus = "#268bd2"
selection = "rgba(7, 54, 66, 0.8)"

# 阴影和其他UI变量
shadow_sm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)"
font_family = "'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace"
border_radius = "6px"
border_radius_lg = "8px"
