[theme]
name = "tokyo-night"
theme_type = "dark"



[theme.ansi]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[theme.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[theme.syntax]
comment = "#565f89"
string = "#9ece6a"
number = "#ff9e64"
keyword = "#bb9af7"
function = "#7aa2f7"
variable = "#c0caf5"
type_name = "#7dcfff"
operator = "#89ddff"

[theme.ui]
# Tokyo Night 背景色层次
bg_100 = "#16161e"
bg_200 = "#1a1b26"
bg_300 = "#1f2335"
bg_400 = "#24283b"
bg_500 = "#2a2f41"
bg_600 = "#32374a"
bg_700 = "#414868"

# 边框层次
border_200 = "rgba(36, 40, 59, 0.3)"
border_300 = "rgba(36, 40, 59, 0.5)"
border_400 = "rgba(36, 40, 59, 0.7)"

# 文本层次
text_100 = "#ffffff"
text_200 = "#c0caf5"
text_300 = "#a9b1d6"
text_400 = "#9aa5ce"
text_500 = "#565f89"

# 状态颜色
primary = "#7aa2f7"
primary_hover = "#6b8aed"
primary_alpha = "rgba(122, 162, 247, 0.1)"
success = "#9ece6a"
warning = "#e0af68"
error = "#f7768e"
info = "#7dcfff"

# 交互状态
hover = "#1f2335"
active = "#24283b"
focus = "#7aa2f7"
selection = "rgba(51, 70, 124, 0.8)"

# 阴影和其他UI变量
shadow_sm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)"
font_family = "'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace"
border_radius = "6px"
border_radius_lg = "8px"
